// CYSPA LinkedIn-Visuals Oktober 2026, CI v3.0
// Inhalte je Visual. Layouts in build.mjs.
// Copy-Regeln CI v3: kein Gedankenstrich im Satzfluss, ss statt ß, keine Ausrufezeichen,
// keine Zahl ohne Quelle. Headlines zweizeilig: [Prämisse, Drehung].

export const VISUALS = [
  // ------------------------------------------------------------ Batch 1 (Freigabepakete)
  {
    nr: '07', slug: 'nis2', file: '2026-09-29-p06-nis2',
    series: 'REGULATORIK IM KLARTEXT',
    format: 'fact', variant: 'rows',
    kicker: 'Drei Wege in die Schweiz',
    title: ['NIS2 ist EU-Recht.', 'Und erreicht die Schweiz trotzdem.'],
    rows: [
      { pill: 'EU-Tochter', head: 'Tochtergesellschaften in der EU', sub: 'Direkt betroffen, inklusive Pflichten der Führungsebene' },
      { pill: 'Lieferkette', head: 'Anforderungen Ihrer EU-Kunden', sub: 'Als Vertragsklausel, Fragebogen oder Audit-Recht' },
      { pill: 'Marktzugang', head: 'Dienste für EU-Kunden', sub: 'Gemessen an den Anforderungen der Kunden' },
    ],
    note: { pill: 'Schweiz', text: 'Parallel gilt die ISG-Meldepflicht: Betreiber kritischer Infrastrukturen melden Cyberangriffe seit 1. April 2025 innert 24 Stunden dem BACS.' },
    source: 'Quellen: Richtlinie (EU) 2022/2555 · ISG Art. 74a ff.',
  },
  {
    nr: '09', slug: 'pentest', file: '2026-10-06-p09-pentest',
    series: 'LESSONS FROM THE FIELD',
    format: 'fact', variant: 'rows',
    kicker: 'Was sich in Sicherheitstests wiederholt',
    title: ['Kein Exploit nötig.', 'Ein Login reicht.'],
    rows: [
      { pill: 'Identität', head: 'Zugänge ohne MFA', sub: 'Vor allem an Nebeneingängen wie VPN, Fernwartung, technischen Konten' },
      { pill: 'Identität', head: 'Wiederverwendete Passwörter', sub: 'Kombiniert mit Zugangsdaten aus alten Datenlecks' },
      { pill: 'Angriffsfläche', head: 'Vergessene, extern erreichbare Systeme', sub: 'Der Testserver von damals, das Portal des abgelösten Systems' },
      { pill: 'Rechte', head: 'Zu breite Berechtigungen', sub: 'Einmal Fuss gefasst, ist der Weg zu mehr Rechten kurz' },
    ],
    closing: 'Identitäten und Angriffsfläche zuerst. Dann der Rest.',
    source: 'Befundklassen aus der Praxis, ohne Kundenbezug',
  },
  {
    nr: '10', slug: 'tabletop', file: '2026-10-08-p12-tabletop',
    pdfTitle: 'Tabletop-Übung: Aus Plan wird Fähigkeit',
    series: 'EXECUTIVE BRIEFING',
    format: 'carousel',
    slides: [
      { t: 'cover', title: ['Samstag, 06:40 Uhr.', 'Wer entscheidet jetzt was?'],
        sub: 'Warum eine Tabletop-Übung Ihrem Führungsteam 90\u00a0Minuten wert ist' },
      { t: 'compare', label: 'Das Format',
        lead: 'Eine Tabletop-Übung ist eine Entscheidungsübung.',
        ok: { head: 'Sie testet die Organisation.', body: 'Entscheide, Rollen, Kommunikation. Mit den richtigen Personen am Tisch.' },
        no: { head: 'Sie testet nicht die Firewall.', body: 'Keine Technik-Simulation. Kein System wird angefasst.' } },
      { t: 'point', label: 'Typische Erkenntnis 1', title: 'Unklare Befugnisse',
        checks: ['Wer darf Systeme vom Netz nehmen, auch wenn das Geschäft steht?', 'Wer gibt Externen den Auftrag, und bis zu welchem Betrag?'] },
      { t: 'point', label: 'Typische Erkenntnis 2', title: 'Kommunikation ohne E-Mail',
        checks: ['Wie erreichen Sie Mitarbeitende und Kunden, wenn E-Mail und Chat betroffen sind?', 'Wo liegen die Notfallkontakte?'] },
      { t: 'blocks', label: 'Typische Erkenntnis 3 und 4', title: 'Fristen und Dienstleister',
        blocks: [
          { head: 'Meldefristen:', body: 'Wer meldet was bis wann? Datenschutz, Verträge, allenfalls Aufsicht.' },
          { head: 'Der erste Anruf:', body: 'Wer ist zuständig? Und gilt der Support-Vertrag auch am Wochenende?' },
        ] },
      { t: 'cta', title: ['Ein halber Tag.', 'Eine dokumentierte Erkenntnisliste.'],
        list: ['Szenario mit Ihrer Führungsrunde', 'Moderierte Entscheidung', 'Erkenntnisliste mit klaren Verantwortlichkeiten'],
        merk: 'Ihr Incident-Response-Plan ist eine Hypothese. Die Übung ist ihr Test.',
        note: 'Details und Terminanfrage: Link im ersten Kommentar' },
    ],
  },
  {
    nr: '11', slug: 'harvest', file: '2026-10-13-p10-harvest',
    series: 'FUTURE SECURITY',
    format: 'fact', variant: 'timeline',
    kicker: '«Harvest now, decrypt later»',
    title: ['Heute abgefangen.', 'Morgen entschlüsselt.'],
    steps: [
      { when: 'Heute', head: 'Abfangen', sub: 'Verschlüsselter Datenverkehr wird aufgezeichnet', hot: true },
      { when: 'Jahrelang', head: 'Speichern', sub: 'Aufzeichnen und Lagern ist günstig' },
      { when: 'Morgen', head: 'Entschlüsseln', sub: 'Sobald Quantencomputer heutige Public-Key-Verfahren brechen' },
    ],
    question: 'Wie lange müssen Ihre Daten vertraulich bleiben?',
    source: 'Erster Schritt im Beitrag: das Krypto-Inventar',
  },
  {
    nr: '12', slug: 'partner-planb', file: '2026-10-15-p11-partner-planb',
    series: 'INSIDE CYSPA',
    format: 'fact', variant: 'rows',
    kicker: 'Vier Prinzipien, an denen wir uns messen lassen',
    title: ['Was «Partner»', 'für uns bedeutet.'],
    numbered: true,
    rows: [
      { head: 'Prioritäten statt Papier', sub: 'Jedes Ergebnis sagt, was zuerst kommt und warum' },
      { head: 'Sicherheit im Massstab des Unternehmens', sub: 'Die Massnahmen mit der grössten Wirkung fürs Geld' },
      { head: 'Befähigen statt abhängig machen', sub: 'Ihr Team kann nach dem Mandat mehr als vorher' },
      { head: 'Klartext im Management-Report', sub: 'Risiken in Geschäftssprache, Entscheidungsvorlagen statt Techniklisten' },
    ],
    source: 'CYSPA · Cyber Security Partners',
  },
  // ------------------------------------------------------------ Neue Posts 20.–29.10.2026
  {
    nr: '13', slug: 'passwordless', file: '2026-10-20-p01-passwordless',
    series: 'QUICK TIP',
    format: 'fact', variant: 'timeline', small: true,
    kicker: 'Der Weg zu Passkeys in vier Schritten',
    title: ['Was man nicht eintippen kann,', 'kann auch keine gefälschte Seite abgreifen.'],
    steps: [
      { when: 'Schritt 1', head: 'Ein eigenes Passwort pro Konto, ohne Ausnahme', hot: true },
      { when: 'Schritt 2', head: 'Passwort-Manager für alle Mitarbeitenden', hot: true },
      { when: 'Schritt 3', head: 'Phishing-resistente MFA, zuerst für Admin-Konten' },
      { when: 'Schritt 4', head: 'Passkeys für alle, Passwort-Logins schrittweise abschalten' },
    ],
    legend: 'Schritt 1 und 2 lassen sich ohne grosses Projekt starten.',
    source: 'Quellen: W3C WebAuthn Level 3 · NIST SP 800-63B-4',
  },
  {
    nr: '14', slug: 'it-vertrag', file: '2026-10-22-p04-it-vertrag',
    series: 'RESILIENZ KONKRET',
    format: 'fact', variant: 'rows', compact: true,
    kicker: 'Fünf Fragen vor der nächsten Verlängerung',
    title: ['Lesen Sie den IT-Vertrag,', 'bevor Sie ihn im Ernstfall brauchen.'],
    rows: [
      { pill: 'Bereitschaft', head: 'Reaktion auch nachts und am Wochenende?' },
      { pill: 'Kosten', head: 'Vorfall im Vertrag oder nach Aufwand?' },
      { pill: 'Zugang', head: 'Ihr Zugang ohne den Dienstleister?' },
      { pill: 'Spuren', head: 'Wer sichert die Spuren?' },
      { pill: 'Spezialisten', head: 'Wer zieht Spezialisten bei?' },
    ],
    closing: 'Die Klärung schützt beide Seiten.',
    source: 'Selbstcheck vor der Vertragsverlängerung',
  },
  {
    nr: '15', slug: 'gastkonten', file: '2026-10-27-p05-gastkonten',
    pdfTitle: 'Gastkonten in Entra ID: 5 Prüfpunkte',
    series: 'MICROSOFT SECURITY PRAXIS',
    format: 'carousel',
    slides: [
      { t: 'cover', title: ['Wer darf in Ihrem Tenant', 'Gäste einladen?'],
        sub: 'Standard in Entra ID: alle Benutzer, auch Gäste. Fünf Prüfpunkte für Ihre Gastkonten.' },
      { t: 'point', num: '1', label: 'Prüfpunkt 1', title: 'Gäste sichtbar machen',
        body: 'Benutzerliste nach Benutzertyp «Guest» filtern und die letzte Anmeldung einblenden. Jedes inaktive Konto braucht einen Entscheid.',
        setting: 'Last interactive sign-in time' },
      { t: 'point', num: '2', label: 'Prüfpunkt 2', title: 'Einladen eingrenzen',
        body: 'Nur festgelegte Rollen laden ein. Für Fachbereiche gibt es die Rolle Guest Inviter, ohne weitere Admin-Rechte.',
        setting: 'Guest invite settings' },
      { t: 'point', num: '3', label: 'Prüfpunkt 3', title: 'Sicht der Gäste begrenzen',
        body: 'Standard ist «eingeschränkt». Die strengste Stufe zeigt Gästen nur ihr eigenes Profil. Vorher Zusammenarbeit testen.',
        setting: 'Guest user access restrictions' },
      { t: 'point', num: '4', label: 'Prüfpunkt 4', title: 'Jeder Gast hat einen Sponsor',
        body: 'Wer einlädt, wird standardmässig Sponsor. Pflegen Sie das Feld, damit klar ist, wer über das Konto entscheidet.',
        setting: 'Sponsors' },
      { t: 'cta', label: 'Prüfpunkt 5', title: 'Regelmässig bestätigen',
        body: 'Access Reviews lassen Verantwortliche den Bedarf bestätigen (Lizenz prüfen). Ohne Lizenz: Liste pro Quartal, Entscheid im IT-Meeting.',
        merk: 'Selbstcheck: Wie viele Gäste haben sich seit 90 Tagen nicht angemeldet?' },
    ],
  },
  {
    nr: '16', slug: 'roadmap', file: '2026-10-29-p08-roadmap',
    pdfTitle: 'Die Security-Roadmap auf einer Seite',
    series: 'AUS DEM CISO-ALLTAG',
    format: 'carousel',
    slides: [
      { t: 'cover', title: ['Passt Ihre Security-Roadmap', 'auf eine Seite?'],
        sub: 'Drei Horizonte, die Geschäftsleitung und IT gleich lesen. Rechtzeitig vor dem Budgetentscheid.' },
      { t: 'compare', label: 'Warum eine Seite',
        lead: 'Eine Seite macht die Roadmap entscheidbar.',
        ok: { head: 'Entscheidbar.', body: 'Die Geschäftsleitung sieht Reihenfolge, Aufwand und Wirkung und kann Ja oder Nein sagen.' },
        no: { head: 'Nicht: die lange Liste.', body: 'Massnahmen ohne Reihenfolge verschieben den Entscheid nur.' } },
      { t: 'horizon', num: '3', unit: 'Monate', title: 'Stabilisieren',
        body: 'Offene Türen schliessen, ohne grosses Projekt. Zum Beispiel:',
        checks: ['Konten ohne zweiten Anmeldefaktor', 'Zu viele Admin-Konten', 'Ein echter Test der Datenwiederherstellung'] },
      { t: 'horizon', num: '6', unit: 'Monate', title: 'Aufbauen',
        body: 'Vorhaben mit Projektcharakter. Zum Beispiel:',
        checks: ['Überwachung mit klarer Reaktion', 'Berechtigungskonzept', 'Notfallorganisation'] },
      { t: 'horizon', num: '12', unit: 'Monate', title: 'Verankern',
        body: 'Was Reife dauerhaft macht. Zum Beispiel:',
        checks: ['Reporting an die Geschäftsleitung', 'Jährliche Übung', 'Anforderungen an Lieferanten'] },
      { t: 'cta', title: 'Pro Zeile drei Angaben',
        list: ['Welches Risiko sinkt?', 'Wer ist verantwortlich?', 'Was kostet es, intern und extern?'],
        merk: 'Eine Roadmap ist ein Entscheid über Reihenfolge, keine Wunschliste.',
        note: 'Erstgespräch: Link im ersten Kommentar' },
    ],
  },
];
